# Generated by Django 5.0.4 on 2024-04-29 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_like_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
