# Generated by Django 5.0.4 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='caption',
            field=models.TextField(null=True),
        ),
    ]
